import re
f = open('data.txt', 'r', encoding = "utf-8")
data = f.read()
name = re.search(r'Филиал\sТОО\s\w+\s\w+', data)
bin = re.search(r'БИН\s\d+', data)
print('1. Name of the company: ' + name.group())
print('2.BIN namber: ' + bin.group())
items = re.findall(r'\d+\.\n(.*)', data)
count = re.findall(r'(\d),\d{3}', data)
many = re.findall(r'x\s([\d\s]+,\d+)', data)
total = re.findall(r'Стоимость\n([\d\s]+,\d+)', data)
for i in range(len(items)):
    print("1.Title: " + items[i])
    print("2.count: " + count[i])
    print("3. Unit price: " + many[i])
    print("4. Total price: " + total[i])
dat = re.search(r'Время:\s\d+.\d+.\d+\s\d+:\d+:\d+', data)
address = re.search(r'г.\s\w+\-\w+,\w+,\s\w+\s\w+,\d+,\s\w+\-\d', data)
print("4. Date: " + dat.group())
print("5. Address: " + address.group())
